run:
	tsc --target esnext --outFile .temp/app.js ./topics/${topic}.ts && node ./.temp/app.js
play:
	tsc --target esnext --outFile .temp/playground.js ./playground.ts && node ./.temp/playground.js
ptn:
	tsc --target esnext --outFile .temp/app.js ./patterns/${pattern}.ts && node ./.temp/app.js
