local co = coroutine.create(function()
  print("Hello, world!")
  coroutine.yield()
  print("Hello, again!")
end)

print("Before starting coroutine")
coroutine.resume(co)
print("After first resume")
coroutine.resume(co)
print("After second resume")
